'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Provider } from 'react-redux';

import '@/assets/styles/globals.scss';

import {  StoreProvider } from '@/components/ui/chatStoreProvider';

import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </StoreProvider>
  );
}
